"""
Creates Gemma 4 finetuning datasets for AI-song detection.

Outputs JSONL files in the Gemma 4 messages format (audio_url instead of
audio array — load and resample during training).

Splits:
  finetuning/test/       — unique songs from v2 annotations
  finetuning/training/   — 80 % of annotation-subset-without-v1-or-v2
  finetuning/validation/ — 20 % of annotation-subset-without-v1-or-v2
"""

import json
import random
from pathlib import Path

random.seed(42)

BASE = Path(__file__).parent

ANNOTATION_SUBSET = BASE / "annotation-subset"
NO_V1_V2_DIR = BASE / "annotation-subset-without-v1-or-v2"
V2_ANNOTATIONS = BASE / "v2" / "annotations_export_2026-04-20.json"
FINETUNING_DIR = BASE / "finetuning"

# --- field names for each source file ----------------------------------
ID_FIELD = {
    "human_songs.jsonl": "uuid",
    "suno_subset.jsonl": "id",
    "udio_subset.jsonl": "id",
    "sonauto_subset.jsonl": "id",
    "mureka_subset.jsonl": "uuid",
}
# Primary audio URL field per file; fallback to "audio_url" if missing
AUDIO_FIELD = {
    "human_songs.jsonl": "audio_url",
    "suno_subset.jsonl": "audio_url",
    "udio_subset.jsonl": "song_path",
    "sonauto_subset.jsonl": "song_path",
    "mureka_subset.jsonl": "audio_url",
}
SOURCE_MAP = {
    "human_songs.jsonl": "human",
    "suno_subset.jsonl": "suno",
    "udio_subset.jsonl": "udio",
    "sonauto_subset.jsonl": "sonauto",
    "mureka_subset.jsonl": "mureka",
}
FILE_FOR_SOURCE = {v: k for k, v in SOURCE_MAP.items()}

SYSTEM_PROMPT = (
    "You are a music expert specializing in detecting whether a song was "
    "created by a human artist or generated by an AI system. "
    "Listen carefully to the audio and make your determination."
)
USER_PROMPT = (
    "Listen to this song and determine whether it was created by a human artist "
    "or generated by AI. "
    "Respond with only 'real' or 'ai-generated'."
)

TRAIN_RATIO = 0.80


# -----------------------------------------------------------------------
def label_for_source(source: str) -> str:
    return "real" if source == "human" else "ai-generated"


def to_message(audio_url: str, label: str) -> dict:
    """Return a single finetuning example in Gemma 4 messages format."""
    return {
        "messages": [
            {
                "role": "system",
                "content": [{"type": "text", "text": SYSTEM_PROMPT}],
            },
            {
                "role": "user",
                "content": [
                    # audio_url is a URL string; load + resample to 16 kHz at training time
                    {"type": "audio", "audio_url": audio_url},
                    {"type": "text", "text": USER_PROMPT},
                ],
            },
            {
                "role": "assistant",
                "content": [{"type": "text", "text": label}],
            },
        ]
    }


def write_jsonl(path: Path, records: list[dict]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w") as f:
        for rec in records:
            f.write(json.dumps(rec, ensure_ascii=False) + "\n")
    print(f"  Wrote {len(records):>6,} records → {path.relative_to(BASE)}")


# -----------------------------------------------------------------------
# 1. BUILD TEST SET FROM V2 ANNOTATIONS
# -----------------------------------------------------------------------
print("=== Building test set from v2 ===")

# Load annotation-subset index (uuid/id → song_dict) for each source
# Also store which audio field to use per source
subset_index: dict[str, dict[str, dict]] = {}  # source → {id: song_dict}
audio_field_for_source: dict[str, str] = {}
for filename, id_field in ID_FIELD.items():
    source = SOURCE_MAP[filename]
    subset_index[source] = {}
    audio_field_for_source[source] = AUDIO_FIELD[filename]
    with open(ANNOTATION_SUBSET / filename) as f:
        for line in f:
            line = line.strip()
            if line:
                song = json.loads(line)
                subset_index[source][song[id_field]] = song

# Collect unique songs from v2 annotations
v2_annotations = json.load(open(V2_ANNOTATIONS))
v2_unique: dict[str, str] = {}  # song_id → source
for ann in v2_annotations:
    sid = ann["song_id"]
    if sid not in v2_unique:
        v2_unique[sid] = ann["song_source"]

test_records: list[dict] = []
missing = 0
for song_id, source in v2_unique.items():
    # song_id looks like "suno_<uuid>" or "human_<uuid>"
    raw_id = song_id.split("_", 1)[1]
    song = subset_index.get(source, {}).get(raw_id)
    if song is None:
        missing += 1
        continue
    audio_url = song.get(audio_field_for_source[source], "")
    if not audio_url:
        missing += 1
        continue
    test_records.append(to_message(audio_url, label_for_source(source)))

test_records.sort(key=lambda r: r["messages"][1]["content"][0]["audio_url"])
write_jsonl(FINETUNING_DIR / "test" / "data.jsonl", test_records)
if missing:
    print(f"  Warning: {missing} v2 songs not found in annotation-subset (skipped)")

# -----------------------------------------------------------------------
# 2. BUILD TRAINING / VALIDATION FROM annotation-subset-without-v1-or-v2
# -----------------------------------------------------------------------
print("\n=== Building training / validation splits ===")

all_no_v2: list[dict] = []
for filename, id_field in ID_FIELD.items():
    source = SOURCE_MAP[filename]
    label = label_for_source(source)
    audio_field = AUDIO_FIELD[filename]
    with open(NO_V1_V2_DIR / filename) as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            song = json.loads(line)
            audio_url = song.get(audio_field, "")
            if not audio_url:
                continue
            all_no_v2.append(to_message(audio_url, label))

random.shuffle(all_no_v2)

split_idx = int(len(all_no_v2) * TRAIN_RATIO)
training = all_no_v2[:split_idx]
validation = all_no_v2[split_idx:]

write_jsonl(FINETUNING_DIR / "training" / "data.jsonl", training)
write_jsonl(FINETUNING_DIR / "validation" / "data.jsonl", validation)

print(f"\nDone. Total: {len(all_no_v2):,} | Train: {len(training):,} | Val: {len(validation):,}")
